
-- Version: 0.0.1 | Update at: 2026-06-27 12:51:38
CREATE TABLE `system_setting` (`name` varchar(170) COMMENT '设置名称',`description` varchar(170) COMMENT '设置描述',`value` varchar(170) COMMENT '设置值',UNIQUE INDEX `uk_system_setting_name` (`name`));
CREATE TABLE `system_role` (`id` bigint unsigned AUTO_INCREMENT COMMENT '自增编号',`created_at` datetime(3) NULL COMMENT '创建时间',`updated_at` datetime(3) NULL COMMENT '更新时间',`deleted_at` datetime(3) NULL COMMENT '删除时间',`name` varchar(64) NOT NULL COMMENT '角色名称',`description` varchar(255) NOT NULL DEFAULT '' COMMENT '角色描述',`status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '角色状态（0：禁用，1：启用）',PRIMARY KEY (`id`),INDEX `idx_created_at` (`created_at`),INDEX `idx_updated_at` (`updated_at`),INDEX `idx_deleted_at` (`deleted_at`),UNIQUE INDEX `uk_system_role_name` (`name`));
CREATE TABLE `system_menu` (`id` bigint unsigned AUTO_INCREMENT COMMENT '自增编号',`name` varchar(64) NOT NULL DEFAULT '' COMMENT '菜单名称',`path` varchar(128) NOT NULL COMMENT '菜单路径',`icon` varchar(128) NOT NULL DEFAULT '' COMMENT '菜单图标',`parent_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '父id',PRIMARY KEY (`id`),UNIQUE INDEX `uk_system_menu_name_path` (`name`,`path`),INDEX `idx_system_menu_parent_id` (`parent_id`));
CREATE TABLE `system_role_menu` (`system_menu_id` bigint unsigned COMMENT '自增编号',`system_role_id` bigint unsigned COMMENT '自增编号',PRIMARY KEY (`system_menu_id`,`system_role_id`));
CREATE TABLE `system_api_category` (`id` bigint unsigned AUTO_INCREMENT COMMENT '自增编号',`name` varchar(64) NOT NULL DEFAULT '' COMMENT '接口类型名称',`parent_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '父id',PRIMARY KEY (`id`),UNIQUE INDEX `uk_system_api_category_name` (`name`),INDEX `idx_system_api_category_parent_id` (`parent_id`));
CREATE TABLE `system_api` (`id` bigint unsigned AUTO_INCREMENT COMMENT '自增编号',`name` varchar(64) NOT NULL DEFAULT '' COMMENT '接口名称',`method` varchar(16) NOT NULL DEFAULT '' COMMENT '请求方法',`api` varchar(255) NOT NULL DEFAULT '' COMMENT '接口URI',`is_auth_api` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否需要授权接口（0：否，1：是）',`system_api_category_id` bigint unsigned NOT NULL COMMENT '接口分类ID',PRIMARY KEY (`id`),INDEX `idx_system_api_name` (`name`),UNIQUE INDEX `uk_system_api_method_api` (`method`,`api`),INDEX `idx_system_api_category_id` (`system_api_category_id`));
CREATE TABLE `user` (`id` bigint unsigned AUTO_INCREMENT COMMENT '自增编号',`created_at` datetime(3) NULL COMMENT '创建时间',`updated_at` datetime(3) NULL COMMENT '更新时间',`deleted_at` datetime(3) NULL COMMENT '删除时间',`nickname` varchar(64) NOT NULL DEFAULT '' COMMENT '昵称',`username` varchar(64) NOT NULL COMMENT '用户名',`mobile` varchar(20) NOT NULL COMMENT '手机号',`hide_mobile` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否隐藏手机号（0：否，1：是）',`email` varchar(100) NOT NULL COMMENT '邮箱',`password` varchar(255) NOT NULL DEFAULT '' COMMENT '密码',`gender` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '性别（0：未知，1：男，2：女）',`avatar_url` varchar(255) NOT NULL DEFAULT '' COMMENT '头像',`last_login_ip` varchar(45) NOT NULL DEFAULT '' COMMENT '最后登录IP',`last_login_at` datetime COMMENT '最后登录时间',`status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '用户状态（0：禁用，1：启用）',`expire_at` datetime COMMENT '过期时间',`system_role_id` bigint unsigned NOT NULL COMMENT '角色ID',PRIMARY KEY (`id`),INDEX `idx_created_at` (`created_at`),INDEX `idx_updated_at` (`updated_at`),INDEX `idx_deleted_at` (`deleted_at`),INDEX `idx_user_nickname` (`nickname`),UNIQUE INDEX `uk_user_username` (`username`),UNIQUE INDEX `uk_user_mobile` (`mobile`),UNIQUE INDEX `uk_user_email` (`email`),INDEX `idx_user_last_login_at` (`last_login_at`),INDEX `idx_user_expire_at` (`expire_at`),INDEX `idx_user_role_id` (`system_role_id`));
CREATE TABLE `user_extra_api` (`id` bigint unsigned AUTO_INCREMENT COMMENT '自增编号',`created_at` datetime(3) NULL COMMENT '创建时间',`updated_at` datetime(3) NULL COMMENT '更新时间',`deleted_at` datetime(3) NULL COMMENT '删除时间',`grant_type` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '授权类型（1：额外授权，2：取消授权）',`user_id` bigint unsigned NOT NULL COMMENT '用户ID',`system_api_id` bigint unsigned NOT NULL COMMENT '接口ID',PRIMARY KEY (`id`),INDEX `idx_created_at` (`created_at`),INDEX `idx_updated_at` (`updated_at`),INDEX `idx_deleted_at` (`deleted_at`),INDEX `idx_user_extra_api_grant_type` (`grant_type`),UNIQUE INDEX `uk_user_extra_api_user_api` (`user_id`,`system_api_id`));
CREATE TABLE `user_extra_menu` (`id` bigint unsigned AUTO_INCREMENT COMMENT '自增编号',`created_at` datetime(3) NULL COMMENT '创建时间',`updated_at` datetime(3) NULL COMMENT '更新时间',`deleted_at` datetime(3) NULL COMMENT '删除时间',`grant_type` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '授权类型（1：额外授权，2：取消授权）',`user_id` bigint unsigned NOT NULL COMMENT '用户ID',`system_menu_id` bigint unsigned NOT NULL COMMENT '菜单ID',PRIMARY KEY (`id`),INDEX `idx_created_at` (`created_at`),INDEX `idx_updated_at` (`updated_at`),INDEX `idx_deleted_at` (`deleted_at`),INDEX `idx_user_extra_menu_grant_type` (`grant_type`),UNIQUE INDEX `uk_user_extra_menu_user_menu` (`user_id`,`system_menu_id`));
